name: RTL Sanity Check

on:
  push:
  pull_request:

jobs:
  rtl_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Compile UART RTL Only
        run: |
          iverilog -g2012 \
          UART-Protocol-V1/rtl/*.sv \
          -o rtl_check.out
